### Create Developer
POST http://localhost:3000/api/developers
Content-Type: application/json

{
  "name": "John Doe",
  "contactInfo": "0789633432",
  "email": "johndoe@example.com",
  "password": "securepassword"
}


### Get All Developers
GET http://localhost:3000/api/developers

### Get Developer by ID
GET http://localhost:3000/api/developers/{DeveloperID}

### Update Developer
PUT http://localhost:3000/api/developers/{DeveloperID}
Content-Type: application/json

{
  "name": "Jane Doe",
  "contactInfo": "janedoe@example.com"
}

### Delete Developer
DELETE http://localhost:3000/api/developers/{9210065a-96d9-4e51-b7e9-64eb66f7d0ea}
