### Create Developer
POST http://localhost:3000/api/developers
Content-Type: application/json

{
  "name": "melo",
  "contactInfo": "0789883432",
  "email": "melo@example.com",
  "password": "securepassword"
}


### Get All Developers
GET http://localhost:3000/api/developers

### Get Developer by ID
GET http://localhost:3000/api/developers/{353aed62-1ee8-43ed-8e83-4e60bd60dab5}

### Update Developer
PUT http://localhost:3000/api/developers/{DeveloperID}
Content-Type: application/json

{
  "name": "Jane Doe",
  "contactInfo": "janedoe@example.com"
}

### Delete Developer
DELETE http://localhost:3000/api/developers/{9210065a-96d9-4e51-b7e9-64eb66f7d0ea}
