###Create a new mortgage
POST http://localhost:3000/api/mortgages/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2YjQ5MzdlLTYwNzYtNDZkOC04NWMyLTA1NjQ1OGM5NDFjMiIsImVtYWlsIjoid2hpdG5leWphY2tzNjg1QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NTgwNjI1LCJleHAiOjE3Mzg1ODQyMjV9.pU3k3IhUVpYUp1YKKk0sfQ6tiGkwOZ8EJ-OZDFk-jn8

{
  "userId": "36b4937e-6076-46d8-85c2-056458c941c2",
  "income": 5000,
  "loanAmount": 200000,
  "interestRate": 5.0,
  "loanTermYears": 30,
  "creditScore": 750,
  "projectId": "410e105e-2f52-4eb4-8f0f-9744984aede2"
}


###Get all mortgages
GET http://localhost:3000/api/mortgages/
Content-Type: application/json


###Get mortgage by ID
GET http://localhost:3000/api/mortgages/{0c4c578d-024e-4256-8611-f0e8249ccaef}
Content-Type: application/json


###Update mortgage
PUT http://localhost:3000/api/mortgages/{8b25ece6-f84f-4fa4-944c-67eeb6ed7383}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2YjQ5MzdlLTYwNzYtNDZkOC04NWMyLTA1NjQ1OGM5NDFjMiIsImVtYWlsIjoid2hpdG5leWphY2tzNjg1QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NTgwNjI1LCJleHAiOjE3Mzg1ODQyMjV9.pU3k3IhUVpYUp1YKKk0sfQ6tiGkwOZ8EJ-OZDFk-jn8

{
  "income": 6000,
  "loanAmount": 254000,
  "interestRate": 4.5,
  "loanTermYears": 25,
  "creditScore": 800
}

###Delete mortgage
DELETE http://localhost:3000/api/mortgages/{8b25ece6-f84f-4fa4-944c-67eeb6ed7383}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2YjQ5MzdlLTYwNzYtNDZkOC04NWMyLTA1NjQ1OGM5NDFjMiIsImVtYWlsIjoid2hpdG5leWphY2tzNjg1QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NTgwNjI1LCJleHAiOjE3Mzg1ODQyMjV9.pU3k3IhUVpYUp1YKKk0sfQ6tiGkwOZ8EJ-OZDFk-jn8

### all mortgage for specific user
GET http://localhost:3000/api/mortgages/user/36b4937e-6076-46d8-85c2-056458c941c2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2YjQ5MzdlLTYwNzYtNDZkOC04NWMyLTA1NjQ1OGM5NDFjMiIsImVtYWlsIjoid2hpdG5leWphY2tzNjg1QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM4NTgwNjI1LCJleHAiOjE3Mzg1ODQyMjV9.pU3k3IhUVpYUp1YKKk0sfQ6tiGkwOZ8EJ-OZDFk-jn8
