###Create a new mortgage
POST http://localhost:3000/api/mortgages/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiYzFiNGMwLThkNDYtNGUxNC1hZGFlLTNlODhkMDM3YTNmNSIsImVtYWlsIjoid2hpdG5leUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczODUwNzIzMSwiZXhwIjoxNzM4NTEwODMxfQ.xRWwY_NotB52aNh5vBRDPCSdSf3xfamDOaBrjyLzkt0

{
  "userId": "36b4937e-6076-46d8-85c2-056458c941c2",
  "income": 5000,
  "loanAmount": 200000,
  "interestRate": 5.0,
  "loanTermYears": 30,
  "creditScore": 750,
  "projectId": "410e105e-2f52-4eb4-8f0f-9744984aede2"
}


###Get all mortgages
GET http://localhost:3000/api/mortgages/
Content-Type: application/json


###Get mortgage by ID
GET http://localhost:3000/api/mortgages/{0c4c578d-024e-4256-8611-f0e8249ccaef}
Content-Type: application/json


###Update mortgage
PUT http://localhost:3000/api/mortgages/{0c4c578d-024e-4256-8611-f0e8249ccaef}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiYzFiNGMwLThkNDYtNGUxNC1hZGFlLTNlODhkMDM3YTNmNSIsImVtYWlsIjoid2hpdG5leUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczODUwNzIzMSwiZXhwIjoxNzM4NTEwODMxfQ.xRWwY_NotB52aNh5vBRDPCSdSf3xfamDOaBrjyLzkt0

{
  "income": 6000,
  "loanAmount": 250000,
  "interestRate": 4.5,
  "loanTermYears": 25,
  "creditScore": 800
}

###Delete mortgage
DELETE http://localhost:3000/api/mortgages/{a18f9472-695d-42ba-a71b-6cce581348ef}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiYzFiNGMwLThkNDYtNGUxNC1hZGFlLTNlODhkMDM3YTNmNSIsImVtYWlsIjoid2hpdG5leUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczODUwNzIzMSwiZXhwIjoxNzM4NTEwODMxfQ.xRWwY_NotB52aNh5vBRDPCSdSf3xfamDOaBrjyLzkt0

