### Register a new user (Whitney Navalia)
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Whitney ",
    "email": "whitney@gmail.com",
    "password": "password123"
}

###get all users
GET http://localhost:3000/api/users/
Content-Type: application/json


### Get user by ID (Whitney Navalia)
GET http://localhost:3000/api/users/04b6d592-e2cb-4e2e-a6dc-9ff099e54a61
Content-Type: application/json

### Update user details (Whitney Navalia)
PUT http://localhost:3000/api/users/04b6d592-e2cb-4e2e-a6dc-9ff099e54a61
Content-Type: application/json

{
    "name": "Whitney",
    "email": "whitney@ex.com",
    "role": "developer"
}

###generate code
POST http://localhost:3000/api/users/request-reset-code
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com"
}


### Reset user password (Whitney Navalia)
PUT http://localhost:3000/api/users/reset-password
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com",
  "resetCode": "9fc3b7",
  "newPassword": "newpassword23"
}

### Delete user (Whitney Navalia)
DELETE http://localhost:3000/api/users/577b51b9-808f-44c3-8888-91bb1a7696bc
Content-Type: application/json
