### Register a new user (Whitney Navalia)
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Whitney Navalia",
    "email": "wn.whitneynavalia@gmail.com",
    "password": "password123"
}

###get all users
GET http://localhost:3000/api/users/
Content-Type: application/json


### Get user by ID (Whitney Navalia)
GET http://localhost:3000/api/users/6a3961ea-1110-4c85-91b4-1e359af0e665
Content-Type: application/json

### Update user details (Whitney Navalia)
PUT http://localhost:3000/api/users/6a3961ea-1110-4c85-91b4-1e359af0e665
Content-Type: application/json

{
    "name": "Whitney Navalia Updated",
    "email": "whitney@ex.com",
    "role": "admin"
}

###generate code
POST http://localhost:3000/api/users/request-reset-code
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com"
}


### Reset user password (Whitney Navalia)
PUT http://localhost:3000/api/users/reset-password
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com",
  "resetCode": "e5f4ac",
  "newPassword": "newpassword23"
}

### Delete user (Whitney Navalia)
DELETE http://localhost:3000/api/users/7080142d-aac9-443a-b9af-6869b86a1afc
Content-Type: application/json
