### Register a new user (Whitney Navalia)
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Whitney jack ",
    "email": "whitneyjacks685@gmail.com",
    "password": "password123"
}

###get all users
GET http://localhost:3000/api/users/
Content-Type: application/json


### Get user by ID (Whitney Navalia)
GET http://localhost:3000/api/users/04b6d592-e2cb-4e2e-a6dc-9ff099e54a61
Content-Type: application/json

### Update user details (Whitney Navalia)
PUT http://localhost:3000/api/users/710b2fa5-c7f5-4e38-9c89-e03c0ca12d5c
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "role": "developer",
    "profileImage": "assets/house.jpg"
}

###generate code
POST http://localhost:3000/api/users/request-reset-code
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com"
}


### Reset user password (Whitney Navalia)
PUT http://localhost:3000/api/users/reset-password
Content-Type: application/json

{
  "email": "whitneyjacks685@gmail.com",
  "resetCode": "9fc3b7",
  "newPassword": "newpassword23"
}

### Delete user (Whitney Navalia)
DELETE http://localhost:3000/api/users/5419f411-754e-4c32-a4c5-769ecbece816
Content-Type: application/json
